### ISSUE TITLE
Using browser back key combo '⌘+[' in help crashes desktop application

### ISSUE THREAD

**Issue by NOP64** [mattermost/desktop#1107]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Apple macOS 10.14.6
- Mattermost Desktop App version: 4.2.0 (4.2.0.61)
- Mattermost Server version: 5.17.0

**Steps to reproduce**
1. Open application.
2. Click 'help' link in bottom right.
3. Scroll to bottom to see links.
4. Click on any link to see another page of help text.
5. Press "⌘+[".

**Expected behavior**
Goes back to prior page. Minimally, doesn't crash.

**Observed behavior**

Dialog pops up saying:

```
The Mattermost app quit unexpectedly. Click "Show Details" to learn more or "Reopen" to open the application again.

Internal error: focusedWindow.goBack is not a function
```

Details below:
```
Application: Mattermost 4.2.0
Platform: Darwin 18.7.0 x64
TypeError: focusedWindow.goBack is not a function
    at click (/Applications/Mattermost.app/Contents/Resources/app.asar/main_bundle.js:12806:25)
    at MenuItem.click (/Applications/Mattermost.app/Contents/Resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/Applications/Mattermost.app/Contents/Resources/electron.asar/browser/api/menu.js:29:13)
```

**Possible fixes**

**Comment by amyblais** [comment]
@NOP64 Do you see the same issue on desktop v4.3.1?

**Comment by NOP64** [comment]
Yes, it does. It's a little worse in that it opens the independent help screen *and* it opens the same help document in a browser tab as well. Video attached.
[mm-crash-video.zip](https://github.com/mattermost/desktop/files/3869883/mm-crash-video.zip)

**Comment by amyblais** [comment]
This may be related to issues with keyboard shortcuts that we are working on fixing for v4.3.2 dot release https://github.com/mattermost/desktop/pull/1092.

**Comment by amyblais** [comment]
Actually I can still reproduce this on 4.3.2, opened a ticket here: https://mattermost.atlassian.net/browse/MM-20922.

**Comment by amyblais** [comment]
Closing as this has been addressed, but feel free to re-open this if the issue persists,
