### ISSUE TITLE
[Crash]: _electron.app.setSecureKeyboardEntryEnabled is not a function

### ISSUE THREAD

**Issue by kalvdans** [mattermost/desktop#2857]
### Before you file a crash report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Version 26.2.1 commit: d2266ac109

### Operating System

Ubuntu Linux 22.04.2 LTS x64

### Mattermost Server Version

Mattermost Version: 8.0.1

### What type of crash did you experience?

Uncaught exception (I saw a dialog pop up that said "The Mattermost app quit unexpectedly")

### Crash report details

```shell
Application: Electron 26.2.1 [commit: d2266ac1
]
Platform: Linux 5.19.0-35-generic x64
TypeError: _electron.app.setSecureKeyboardEntryEnabled is not a function
    at IpcMainImpl.handleToggleSecureInput (/home/chn/repo/mattermost-desktop/dist/index.js:73595:17)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89074)
    at WebContents.emit (node:events:513:28)
```

### Log Output

```shell
[2023-09-21 14:25:09.831] [error] Logger Log level set to: info
[2023-09-21 14:25:09.954] [warn]  [Config] Failed to load configuration file from the filesystem. Using defaults.
[2023-09-21 14:25:09.955] [warn]  [AutoLauncher] In development mode, autostart config never effects
[2023-09-21 14:25:09.961] [info]  [App.Config] config.autostart has been configured: true
[2023-09-21 14:25:10.588] [info]  [App.Initialize] Autoupgrade disabled: false
[2023-09-21 14:25:10.591] [error] [MainWindow] Error: ENOENT: no such file or directory, open '/home/chn/.config/Electron/bounds-info.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at Object.readFileSync (node:fs:469:35)
    at Object.readFileSync (node:electron/js2c/asar_bundle:2:9212)
    at MainWindow.getSavedWindowState (/home/chn/repo/mattermost-desktop/dist/index.js:83384:51)
    at MainWindow.init (/home/chn/repo/mattermost-desktop/dist/index.js:83187:36)
    at MainWindow.show (/home/chn/repo/mattermost-desktop/dist/index.js:83311:14)
    at initializeAfterAppReady (/home/chn/repo/mattermost-desktop/dist/index.js:73334:23)
    at initialize (/home/chn/repo/mattermost-desktop/dist/index.js:73088:9)
[2023-09-21 14:25:10.656] [info]  [ServerDropdownView] init
[2023-09-21 14:25:10.675] [warn]  [i18nManager] Failed to set new language en-US
[2023-09-21 14:25:10.676] [warn]  [i18nManager] Failed to set new language SE
[2023-09-21 14:25:10.712] [error] [App.Utils] clearAppCache TypeError: Object has been destroyed
[2023-09-21 14:25:11.292] [info]  [ModalView] [welcomeScreen] preloading with /home/chn/repo/mattermost-desktop/dist/desktopAPI.js
[2023-09-21 14:25:11.786] [info]  [App.Initialize] Added Extension:  React Developer Tools
[2023-09-21 14:25:55.068] [warn]  [AutoLauncher] In development mode, autostart config never effects
[2023-09-21 14:25:55.077] [info]  [App.Config] config.autostart has been configured: true
[2023-09-21 14:25:55.079] [warn]  [AutoLauncher] In development mode, autostart config never effects
[2023-09-21 14:25:55.090] [info]  [App.Config] config.autostart has been configured: true
[2023-09-21 14:25:55.156] [warn]  [AutoLauncher] In development mode, autostart config never effects
[2023-09-21 14:25:55.162] [info]  [App.Config] config.autostart has been configured: true
[2023-09-21 14:30:44.932] [error] Logger Log level set to: info
[2023-09-21 14:30:45.068] [warn]  [AutoLauncher] In development mode, autostart config never effects
[2023-09-21 14:30:45.073] [info]  [App.Config] config.autostart has been configured: true
[2023-09-21 14:30:45.537] [info]  [App.Initialize] Autoupgrade disabled: false
[2023-09-21 14:30:45.597] [info]  [ServerDropdownView] init
[2023-09-21 14:30:45.608] [warn]  [i18nManager] Failed to set new language en-US
[2023-09-21 14:30:45.609] [warn]  [i18nManager] Failed to set new language SE
[2023-09-21 14:30:45.643] [warn]  [AutoLauncher] In development mode, autostart config never effects
[2023-09-21 14:30:45.649] [info]  [App.Config] config.autostart has been configured: true
[2023-09-21 14:30:45.664] [info]  [App.Initialize] Added Extension:  React Developer Tools
[2023-09-21 14:30:46.311] [warn]  [AutoLauncher] In development mode, autostart config never effects
[2023-09-21 14:30:46.318] [info]  [App.Config] config.autostart has been configured: true
```

### Additional Information

I was going to input username and password to gitlab, during the oauth authentication to our mattermost server.

**Comment by francislavoie** [comment]
I'm getting the same on the latest RC

```
Application: Mattermost 5.5.1-rc.2 [commit: e4d05b5
]
Platform: Linux 6.4.6-76060406-generic x64
TypeError: _electron.app.setSecureKeyboardEntryEnabled is not a function
    at IpcMainImpl.handleToggleSecureInput (/opt/Mattermost/resources/app.asar/index.js:93990:17)
    at IpcMainImpl.emit (node:events:513:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89074)
    at WebContents.emit (node:events:513:28)
```

**Comment by glemignot** [comment]
I can confirm getting the same problem with both 5.5.1-rc.2 and 5.5.1-rc.1 (on Debian GNU/Linux AMD64) but it works fine with 5.5.0.

**Comment by njnatale-lm** [comment]
+1, seeing this on Windows as well on 5.5.1 RC2.
